server:
  port: 8763
spring:
  application:
    name: eureka-consumers
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

